/*
 * generated by Xtext 2.12.0
 */
package de.tobias_blaufuss.persistence.ide


/**
 * Use this class to register ide components.
 */
class PersistenceIdeModule extends AbstractPersistenceIdeModule {
}
