/*
 * generated by Xtext 2.12.0
 */
package de.tobias_blaufuss.persistence


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PersistenceStandaloneSetup extends PersistenceStandaloneSetupGenerated {

	def static void doSetup() {
		new PersistenceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
