/*
 * generated by Xtext 2.12.0
 */
package de.tobias_blaufuss.persistence


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PersistenceRuntimeModule extends AbstractPersistenceRuntimeModule {
}
